name: CI Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: JDK 17 Set Up
      uses: actions/setup-java@v2  
      with: 
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean compile
      working-directory: dr4_11  

    - name: Run tests
      run: mvn test
      working-directory: dr4_11  

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: maven-build
        path: dr4_11/target/*.jar  
